# Generated by Django 5.2 on 2025-05-04 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_slug'),
        ('news', '0002_category_alter_news_options_news_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='categories.category', verbose_name='Категория'),
        ),
    ]
